### ISSUE TITLE
Jump between search results (like cmd f)

### ISSUE THREAD

**Issue by NaBo1985** [dhilt/ngx-ui-scroll#235]
Hey @dhilt ,

![image](https://user-images.githubusercontent.com/68053611/101787730-113e3a00-3b08-11eb-8e12-9b0f2c129150.png)

I would like to implement a search function similar to cmd/ctrl F with the ability to jump between the results in my chat application, I am using the "chat view" which starts from the bottom, when the app loads it fetches a batch of 100 messages.
when the user continues to scroll up he fetches another 100 messages and so on.

this is my code

```typescript

ngOnInit() {
 this.datasource = new Datasource({
    get: (index, count) =>
      this.messageService.request(index, count),
    settings: this.datasourceSettings,
    devSettings: { debug: false }
  });
  this.datasource.adapter.isLoading$
    .pipe(filter(isLoading => !isLoading), take(1))
    .subscribe(() => {
      this.datasource.adapter.relax();
      this.datasource.adapter.fix({ scrollPosition: Infinity }); // scroll bottom
    });
}

```

To clarify the use case, when I search for a word I send a request to the server and receive back the matching message array.
The next step I need to execute is to jump between the messages with the provided search term. 

if the search term is not within the batch of 100 messages i would like to automatically scroll up to the next matching result and so on until we have reached all results.

thanks for your help

**Comment by dhilt** [comment]
@NaBo1985 Basically, if you know the item you want to scroll in and this item does exist in the current Scroller's buffer, you may use [fix-scrollToItem](https://dhilt.github.io/ngx-ui-scroll/#/experimental#adapter-fix-scrollToItem) Adapter API which uses standard scrollIntoView Web API method under the hood:

```js
this.datasource.adapter.fix({
  scrollToItem: ({ data }) => data.id === foundItemId
});
```

In your case I think you need to check if `foundItemId` is buffered:

```js
let isAccessible = false;
this.datasource.adapter.fix({
  updater: ({ data }) =>
    isAccessible = isAccessible || data.id === foundItemId
});
```

Then you need to make one of three steps:
 - scroll to existed item if `isAccessible` is `true`
 - scroll to to the left edge of the viewport if `isAccessible` is `false` and `foundItemId` is less than the first buffered `id`
 - scroll to to the right edge of the viewport if `isAccessible` is `false` and `foundItemId` is more than the first buffered `id`

After this you need to recursively re-run the check-scroll procedure. Let me try to summarize this by the following code:

```js
async scrollToItemById(itemId) {
  const { adapter } = this.myDatasource;
  await adapter.relax();

  let isAccessible = false; // if the required item is in buffer
  let firstItem, lastItem; // first and last buffered items
  let i = 0;
  adapter.fix({
    updater: ({ data }) => {
      isAccessible = isAccessible || data.id === itemId;
      firstItem = i++ === 0 ? data: firstItem;
      lastItem = data;
    }
  });

  if (isAccessible) {
    adapter.fix({ scrollToItem: ({ data }) => data.id === itemId });
    return; // Done!
  }
  
  const isBefore = itemId < firstItem.id; // considering numeric ids
  const isAfter = itemId > lastItem.id;
  adapter.fix({ 
    scrollPosition: isBefore ? -Infinity : Infinity
  });

  // now we need to wait for the Scroller starts and finishes its work
  // and then perform a recursive call
  adapter.isLoading$
    .pipe(filter(isLoading => !isLoading), take(1))
    .subscribe(() => this.scrollToItemById(itemId));
}
```

The `Adapter.fix` method is synchronous currently and we can't rely on its return value or on `relax`, we have to deal with `isLoading$`.

**Comment by NaBo1985** [comment]
Hey @dhilt ,
Thanks for the quick response
I have implemented the scroll to item as you suggested in my own app and it is acting quite buggy.
When I press to scroll the list jumps and breaks the UI 

I managed to reproduce the problem over at stackblitz:
https://stackblitz.com/edit/ngx-ui-scroll-chat-app-pqjftu  

from what I'm noticing the bug acts differently when my position is above and below the index 

any guidance is appreciated

**Comment by dhilt** [comment]
@NaBo1985 As I see, you forgot to unsubscribe via `take(1)`, this forces the UI to re-scroll again and again.

**Comment by NaBo1985** [comment]
@dhilt,  I removed the take(1) just for testing purposes it didn't make a difference when I had it on, can you please press the "scroll to" button and wait for the scroll to finish in the stackblitz demo to see the problem
 
https://stackblitz.com/edit/ngx-ui-scroll-chat-app-pqjftu

**Comment by dhilt** [comment]
@NaBo1985 I'm experiencing a critical difference: without unsubscribing the UI gets stuck. With `take(1)` it works fine for me.  I open the demo, run `scrollToItemById`, wait for it is done, then I scroll top, scroll bottom, and see no issues, UI responds as I would expect. Maybe I'm missing something, and it would be nice if you could provide more details and describe the repro including steps and the difference between expectations and what you get.

**Comment by dudipsh** [comment]
Hi, @dhilt 
@NaBo1985 and i work together on the project ( we add the take(1) ) please 

[![Watch the video]()](https://time-talk-buckets-company-tempcomp2.s3.amazonaws.com/uploads/5fb374e4bcb64f198f5f8144/WhatsApp+Video+2020-12-13+at+08.10.57.mp4)
(like edited )
i added a video  the problem start at 00:46 sec, 
i will try to describe the issue again, 
above the list we have header (Who is supposed to stay there) and  after the scroll complete the header disappeared




```typescript

  async scrollToItemById(itemId) {
    const { adapter } = this.datasource;
    await adapter.relax();

    let isAccessible = false; // if the required item is in buffer
    let firstItem, lastItem; // first and last buffered items
    let i = 0;
    adapter.fix({
      updater: ({ data }) => {
        isAccessible = isAccessible || data.id === itemId;
        firstItem = i++ === 0 ? data : firstItem;
        lastItem = data;
      }
    });

    if (isAccessible) {
      adapter.fix({ scrollToItem: ({ data }) => data.id === itemId });
      return; // Done!
    }

    const isBefore = itemId < firstItem.id; // considering numeric ids
    const isAfter = itemId > lastItem.id;
    adapter.fix({
      scrollPosition: isBefore ? -Infinity : Infinity
    });

    // now we need to wait for the Scroller starts and finishes its work
    // and then perform a recursive call
    adapter.isLoading$
      .pipe(
        filter(isLoading => !isLoading),
        take(1) 
      )
      // .pipe(take(1))
      .subscribe(() => {
        this.scrollToItemById(itemId);
      });
  }

  junp() {
    this.scrollToItemById(850);
  }

```

**Comment by dudipsh** [comment]
thanks @dhilt  its works now! 👍 
#### this code fix the issue

```typescript

    async scrollToItemById(message: Message) {
        const { adapter } = this.datasource;
        await adapter.relax();

        let isAccessible = false; // if the required item is in buffer
        let firstItem, lastItem; // first and last buffered items
        let i = 0;
        adapter.fix({
            updater: ({ data }) => {
                isAccessible = isAccessible || data.uuid === message.uuid;
                firstItem = i++ === 0 ? data : firstItem;
                lastItem = data;
            }
        });

        if (isAccessible) {
            // adapter.fix({ scrollToItem: ({ data }) => data.id === itemId });
            this.datasource.adapter.reload(message.uuid).then(res => {
                console.log(res);
                if (res.success) {
                    this.datasource.adapter.relax();
                }
            });
            return; // Done!
        }

        const isBefore = message.uuid < firstItem.uuid; // considering numeric ids
        const isAfter = message.uuid > lastItem.uuid;
        adapter.fix({
            scrollPosition: isBefore ? -Infinity : Infinity
        });

        // now we need to wait for the Scroller starts and finishes its work
        // and then perform a recursive call
        adapter.isLoading$
            .pipe(
                filter(isLoading => !isLoading),

            )
            .pipe((take(1)))
          //  .pipe(takeUntil(this.destroy$))
            .subscribe(() => {
                this.scrollToId(message.uuid);
                //this.scrollToItemById(itemId);
            });
    }

    private scrollToId(itemId) {
        this.datasource.adapter.reload(itemId).then(res => {
            if (res.success) {
                this.datasource.adapter.relax();
            }
        });
    }
```

**Comment by dhilt** [comment]
@dudipsh Glad to hear this works! By the way, if you use "reload" to show the item when it becomes DOM-accessible, why not to reload when it is not accessible? You don't need to scroll to the portion of data containing your item, you just need to know its index in the dataset and perform "reload(index)". Let the Datasource serve transitions without extra loading of the UI.

**Comment by dudipsh** [comment]
Hi,
@dhilt, turns out that the problem hasn't been fixed, the behavior isn't consistent, if I scrolled to the top to the first ever message and try to jump back to the last massage all the data disappears without any error message.

I've added the auto increment id (uuid) as you suggested (starting with 0)
the first item when the list loads is 0 and the last is the number of items (309 for example)

The chat loads with the last batch of 100 records which consists of 
the first being uuid=308 and the last record being uuid=208.

that means that if i wanted to jump to uuid=100 I cant because it isn't DOM-accessible, so the plan was to scroll up (fetch more) until I reach uuid=100


![image](https://user-images.githubusercontent.com/6501567/102213537-8bdbd080-3edf-11eb-9816-1e5ec04aa323.png)

**Comment by NaBo1985** [comment]
hey @dhilt 
the issue has been solved
thanks for being such a great help as usual
